#spring.application.name=CategoryManagement

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://172.20.0.70:5432/IndexManagement
    hikari:
      username: sa
      password: Abc@123456789
      schema: testcatogy
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    web:
      pageable:
        page-parameter: 1
        size-parameter: 10